Repository simdjson/simdjson, pull requests merged in 2020-10, with the labels that each got.

#1189 add CI fuzzing on arm 64 bit
  .drone.yml
  fuzz/fuzz_implementations.cpp
Labels: fuzzing

#1200 Testing on minimalist alpine (linux) images
  .github/workflows/alpine.yml
  benchmark/linux/linux-perf-events.h
Labels: platform coverage

#1201 simplify fuzzing only dynamically supported implementations
  .github/workflows/fuzzers.yml
  fuzz/build_fuzzer_variants.sh
  fuzz/fuzz_implementations.cpp
  fuzz/fuzz_minifyimpl.cpp
  fuzz/fuzz_utf8.cpp
  fuzz/quick_check.sh
  fuzz/supported_implementations.h
Labels: fuzzing

#1222 new number parsing
  include/simdjson/common_defs.h
  include/simdjson/generic/numberparsing.h
  include/simdjson/internal/jsoncharutils_tables.h
  include/simdjson/internal/numberparsing_tables.h
  src/from_chars.cpp
  src/internal/numberparsing_tables.cpp
  src/simdjson.cpp
  tests/CMakeLists.txt
  tests/basictests.cpp
  tests/numberparsingcheck.cpp
  tests/random_string_number_tests.cpp
Labels: hygiene, platform coverage

#1226 This is a cleaner on-demand documentation (for discussion).
  doc/ondemand.md
Labels: discussion, documentation

#1233 This adds new tests regarding ordering.
  doc/ondemand.md
  tests/ondemand/ondemand_basictests.cpp
Labels: On Demand

#1204 add fuzz element
  .github/workflows/fuzzers.yml
  fuzz/CMakeLists.txt
  fuzz/FuzzUtils.h
  fuzz/Fuzzing.md
  fuzz/fuzz_atpointer.cpp
  fuzz/fuzz_element.cpp
  include/simdjson/dom/element-inl.h
  include/simdjson/dom/element.h
  include/simdjson/padded_string-inl.h
  tests/CMakeLists.txt
  tests/padded_string_tests.cpp
Labels: fuzzing

#1237 Tweaking further the documentation.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/standard-issue-template.md
  doc/ondemand.md
Labels: documentation

#1232 Reenable the on-demand tests and allows us to convert a raw string into a C++ string.
  .circleci/config.yml
  doc/ondemand.md
  include/simdjson/generic/ondemand/field-inl.h
  include/simdjson/generic/ondemand/field.h
  include/simdjson/generic/ondemand/parser-inl.h
  include/simdjson/generic/ondemand/raw_json_string.h
  include/simdjson/generic/stringparsing.h
  tests/ondemand/ondemand_basictests.cpp
Labels: On Demand, documentation, enhancement, test coverage

#1239 Adding a new benchmark for ondemand: distinct user id
  benchmark/bench_ondemand.cpp
  benchmark/distinctuserid/distinctuserid.h
  benchmark/distinctuserid/dom.h
  benchmark/distinctuserid/ondemand.h
  doc/ondemand.md
  tests/ondemand/ondemand_basictests.cpp
Labels: On Demand, benchmarking, discussion, documentation, performance
