Repository simdjson/simdjson, pull requests merged in 2021-04, with the labels that each got.

#1527 This implements string serialization for On Demand instances.
  doc/basics.md
  doc/dom.md
  include/simdjson/generic/ondemand-inl.h
  include/simdjson/generic/ondemand.h
  include/simdjson/generic/ondemand/serialization-inl.h
  include/simdjson/generic/ondemand/serialization.h
  src/to_chars.cpp
  tests/minify_tests.cpp
  tests/ondemand/CMakeLists.txt
  tests/ondemand/ondemand_tostring_tests.cpp
  tools/json2json.cpp
Labels: on demand

#1530 My third attempt at fixing issue 1521 (not being merged due to performance concerns)
  include/simdjson/common_defs.h
  include/simdjson/generic/ondemand/json_iterator-inl.h
  tests/ondemand/ondemand_object_tests.cpp
Labels: bug, on demand, performance

#1536 use github action cache instead of bintray
  .github/workflows/fuzzers.yml
  fuzz/quick_check.sh
Labels: fuzzing

#1534 Document stream: truncate final unfinished document and give access to the number of truncated bytes.
  benchmark/benchmarker.h
  benchmark/statisticalmodel.cpp
  doc/parse_many.md
  include/simdjson/dom/document_stream-inl.h
  include/simdjson/dom/document_stream.h
  include/simdjson/generic/dom_parser_implementation.h
  include/simdjson/generic/ondemand/parser-inl.h
  include/simdjson/internal/dom_parser_implementation.h
  src/arm64/dom_parser_implementation.cpp
  src/fallback/dom_parser_implementation.cpp
  src/generic/stage1/find_next_document_index.h
  src/generic/stage1/json_structural_indexer.h
  src/haswell/dom_parser_implementation.cpp
  src/ppc64/dom_parser_implementation.cpp
  src/westmere/dom_parser_implementation.cpp
  tests/basictests.cpp
  tests/document_stream_tests.cpp
  tests/document_tests.cpp
  tests/errortests.cpp
  tests/parse_many_test.cpp
  tests/readme_examples.cpp
Labels: documentation, ndjson

#1545 Under ARM, it is slightly better to reverse the word once and then extract the bits.
  include/simdjson/arm64/bitmanipulation.h
  src/generic/stage1/json_structural_indexer.h
Labels: performance
